---
version: "2.1"
services:
  code-server:
    build:
      context: .
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/workspace:/config/workspace
      - /path/to/anything/:/config/workspace/anything
    ports:
      - 8441:8443
    restart: unless-stopped
